### ISSUE TITLE
Popup error after uploading CSV file

### ISSUE THREAD

**Issue by okkernoten** [mythirdeye/jtrt-tables#1]
![error](https://cloud.githubusercontent.com/assets/13786940/9259497/d0022c7c-4201-11e5-8f4d-de8b587f8921.jpg)

I get the popup error 'You must first upload a CSV file to convert' every time I want to generate. I tried both ways: uploading a CSV file or using a url to a CSV file.

Can you please help me?

**Comment by okkernoten** [comment]
Oh I needed to save it first. Now it's working. Sorry, my bad :)

**Comment by mythirdeye** [comment]
Hey Okkernoten, glad you were able to figure it out! I was going to comment earlier but I was outside and didn't have time ^^ Let me know if you run into any more issues!
